language: python

python:
  - "2.7"

env:
  - TEST_TYPE=unit

sudo: false

cache:
  directories:
  - $HOME/.cache/pip

install:
  - pip install -r development.txt

script:
  - make $TEST_TYPE

branches:
  only:
    - master
